spring.application.name=users-service
server.port=8081

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/BDAuth}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

application.security.jwt.secret-key=${JWT_SECRET}
application.security.jwt.expiration=${JWT_EXPIRATION}
application.security.jwt.refresh-token.expiration=${REFRESH_TOKEN_EXPIRATION}

application.security.lock.max-failed-attempts=${MAX_FAILED_ATTEMPTS}
application.security.lock.time-minutes=${LOCK_TIME_MINUTES}

# Configuración SMTP para Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true