spring.application.name=books-service

spring.datasource.url=jdbc:postgresql://localhost:5432/books_db
spring.datasource.username=books_user
spring.datasource.password=${BOOKS_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

openlibrary.api-url=https://openlibrary.org

deepl.api-key=${DEEPL_API_KEY}